config/routes.rb
Rails.application.routes.draw do
  root :to => 'queues#index'

  resources :queues

  get 'oauths/oauth'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions, except: :new
  get    'login'  => 'user_sessions#new', :as => :login
  post   'login'  => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, except: :new
  get 'signup'  => 'users#new'
  get 'username' => 'users#username'

  resources :teams
  resources :requests

  resources :memberships

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member, class_name: "User"
  belongs_to :team
end

app/models/memberships.rb
class Memberships < ActiveRecord::Base
  belongs_to :member, class_name: "User"
  belongs_to :group
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @memberships = Membership.all

    @all_memberships = Membership.group(:team_id).pluck(:team_id)
  end

  def show
    @membership = Membership.find(params[:id])
  end

  def new
    @membership = Membership.new({member: current_user})
  end

  def edit
    @membership = Membership.find(params[:id])
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :member %>
  <%= f.text_field :member %><br />

  <%= f.label :team %>
  <%= f.text_field :team %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Edit membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<%= link_to "Add membership", new_membership_path, class: "button radius" %>

<table>
  <tbody>
    <% @memberships.each do |membership| %>
    <tr>
      <td><h4>membership <%= link_to "##{membership.id}", membership_path(membership.id) %></h4></td>
      <td><%= link_to 'Edit', edit_membership_path(membership), class: "button secondary" %></td>
      <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' }, class: "button alert" %> <br /></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% @memberships.each do |m| %>
  <%= link_to m.team.name, team_path(m.team) %>: <br />
  <% m.team.members.each do |s| %>
    <%= link_to s.first_name, user_path(s) %><br />
  <% end %><br />
<% end %>
<br />
<br />
<br />

number of memberships: <%= @all_memberships.count %><br /><br />

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<%= @membership.team.name %> - <%= @membership.member.name %>