config/routes.rb
Rails.application.routes.draw do
  root :to => 'queues#index'

  resources :queues

  get 'oauths/oauth'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions, except: :new
  get    'login'  => 'user_sessions#new', :as => :login
  post   'login'  => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, except: :new
  get 'signup'  => 'users#new'
  get 'username' => 'users#username'

  resources :teams
  resources :requests

  resources :memberships

end

app/controllers/queues_controller.rb
class QueuesController < ApplicationController
  def index
    @my_pairing_teams = current_user.teams.where(kind: "daily").order(begin_date: :desc)
    @current_teams = current_user.teams.where(kind: "weekly").where("end_date < ?", Date.today)
  end

  def new
  end

  def edit
  end

  def show
  end

  def delete
  end
end

app/helpers/queues_helper.rb
module QueuesHelper
end

app/views/queues/delete.html.erb
<h1>Queues#delete</h1>
<p>Find me in app/views/queues/delete.html.erb</p>

app/views/queues/edit.html.erb
<h1>Queues#edit</h1>
<p>Find me in app/views/queues/edit.html.erb</p>

app/views/queues/index.html.erb
<div class="row">
  <h4>queued requtest place is here</h4>
  <ul>
    <li>Lorem ipsum dolor sit amet, </li>
    <li>consectetur adipiscing elit, sed do tempor</li>
    <li>incididunt ut  et dolore  aliqua. </li>
    <li>Ut enim ad minim veniam, quis nostrud </li>
    <li> ullamco  nisi ut aliquip</li>
  </ul>
  <%= link_to "Create a team", new_team_path, class: "button radius" %>
</div>

<%= render 'teams/current_teams' %>

<%= render 'teams/my_pairs' %>

app/views/queues/new.html.erb
<h1>Queues#new</h1>
<p>Find me in app/views/queues/new.html.erb</p>

app/views/queues/show.html.erb
<h1>Queues#show</h1>
<p>Find me in app/views/queues/show.html.erb</p>